In [1]:
import pandas as pd

In [2]:
amazon = pd.read_csv("Amazon Sale Report.csv" , index_col=False )

C:\Users\anoir\AppData\Local\Temp\ipykernel_17724\2467940799.py:1: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  amazon = pd.read_csv("Amazon Sale Report.csv" , index_col=False )

In [3]:
amazon.head(5)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [4]:
amazon.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 82.3+ MB

In [5]:
amazon.drop(columns=['index','Sales Channel ','ship-service-level','currency','ship-postal-code','ship-country','Unnamed: 22'],inplace=True)

In [6]:
amazon.isnull().sum()

Order ID              0
Date                  0
Status                0
Fulfilment            0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status     6872
Qty                   0
Amount             7795
ship-city            33
ship-state           33
promotion-ids     49153
B2B                   0
fulfilled-by      89698
dtype: int64

In [7]:
Merchant=amazon[amazon['Fulfilment']=='Merchant']

In [8]:
Merchant.reset_index(drop=True,inplace=True)

In [9]:
Merchant[Merchant['Amount'].isnull()]

,Order ID,Date,Status,Fulfilment,Style,SKU,Category,Size,ASIN,Courier Status,Qty,Amount,ship-city,ship-state,promotion-ids,B2B,fulfilled-by
11,404-5933402-8801952,04-30-22,Cancelled,Merchant,JNE2132,JNE2132-KR-398-XXXL,kurta,3XL,B07JG3CND8,NaN,0,NaN,GUWAHATI,ASSAM,NaN,False,Easy Ship
56,404-7452877-2137949,04-30-22,Cancelled,Merchant,JNE3802,JNE3802-KR-M,kurta,M,B09K3W2LHF,NaN,0,NaN,BENGALURU,KARNATAKA,NaN,False,Easy Ship
115,405-7730926-6032325,04-30-22,Cancelled,Merchant,J0386,J0386-KR-XXXL,kurta,3XL,B09YYLFCP2,NaN,0,NaN,SIKANDARABAD INDUSTRIAL AREA,UTTAR PRADESH,NaN,False,Easy Ship
133,403-5342526-7867558,04-30-22,Cancelled,Merchant,MEN5019,MEN5019-KR-XXXL,kurta,3XL,B08YYQXZHK,NaN,0,NaN,FARIDABAD,HARYANA,NaN,False,Easy Ship
168,408-1348466-1321955,04-30-22,Cancelled,Merchant,JNE2032,JNE2032-KR-205-XXXL,kurta,3XL,B07H6L4CBM,NaN,0,NaN,BENGALURU,KARNATAKA,NaN,False,Easy Ship
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39116,408-6007733-3709905,06-01-22,Cancelled,Merchant,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,NaN,BENGALURU,KARNATAKA,NaN,False,Easy Ship
39188,408-6132516-8957130,06-01-22,Cancelled,Merchant,J0158,J0158-DR-S,Western Dress,S,B091XT968F,NaN,0,NaN,CHENNAI,TAMIL NADU,NaN,False,Easy Ship
39190,404-3225296-2958738,06-01-22,Cancelled,Merchant,JNE3407,JNE3407-KR-XXL,kurta,XXL,B0893FS7QX,NaN,0,NaN,JAUNPUR,UTTAR PRADESH,NaN,False,Easy Ship
39252,408-4182027-2307535,06-01-22,Cancelled,Merchant,JNE3619,JNE3619-KR-S,kurta,S,B091Q8JXX9,NaN,0,NaN,BENGALURU,KARNATAKA,NaN,False,Easy Ship
39263,402-1958677-2521967,06-01-22,Cancelled,Merchant,JNE3568,JNE3568-KR-M,kurta,M,B08KRZRSCL,NaN,0,NaN,Cherukunnu (p.o),KERALA,NaN,False,Easy Ship

In [10]:
Merchant[Merchant['Amount'].isnull()]['Qty'].value_counts()

Qty
0    1736
Name: count, dtype: int64

In [11]:
Merchant[Merchant['Amount'].isnull()]['Status'].value_counts()

Status
Cancelled                       1725
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [12]:
Merchant.drop(Merchant[(Merchant['Amount'].isnull()) & (Merchant['Status']=='Cancelled')].index ,inplace=True)

In [13]:
Merchant[Merchant['Amount'].isnull()]['Status'].value_counts()

Status
Shipped - Delivered to Buyer    8
Shipped - Returned to Seller    3
Name: count, dtype: int64

In [14]:
Merchant['Amount'] = Merchant['Amount'].fillna(0)

In [15]:
Merchant[Merchant['Amount'].isnull()].value_counts()

Series([], Name: count, dtype: int64)

In [16]:
Merchant.isnull().sum()

Order ID             0
Date                 0
Status               0
Fulfilment           0
Style                0
SKU                  0
Category             0
Size                 0
ASIN                 0
Courier Status    5147
Qty                  0
Amount               0
ship-city           13
ship-state          13
promotion-ids     5204
B2B                  0
fulfilled-by         0
dtype: int64

In [17]:
Merchant['Status'].value_counts()

Status
Shipped - Delivered to Buyer     28769
Cancelled                         5136
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending - Waiting for Pick Up      281
Pending                            243
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [18]:
outbound =['Shipped - Delivered to Buyer','Shipped - Picked Up','Pending - Waiting for Pick Up','Shipped - Out for Delivery']
retour   =['Shipped - Returned to Seller','Shipped - Rejected by Buyer','Shipped - Returning to Seller']

In [19]:
stock_list = Merchant['Status'].unique().tolist()
stock_list

['Cancelled',
 'Shipped - Delivered to Buyer',
 'Shipped - Returned to Seller',
 'Shipped - Rejected by Buyer',
 'Shipped - Lost in Transit',
 'Shipped - Out for Delivery',
 'Shipped - Returning to Seller',
 'Shipped - Picked Up',
 'Pending',
 'Pending - Waiting for Pick Up',
 'Shipped - Damaged']

In [20]:
Merchant.sort_values(by='Date')

,Order ID,Date,Status,Fulfilment,Style,SKU,Category,Size,ASIN,Courier Status,Qty,Amount,ship-city,ship-state,promotion-ids,B2B,fulfilled-by
15762,171-7192082-3049169,03-31-22,Cancelled,Merchant,JNE3461,JNE3461-KR-L,kurta,L,B08B3YWTLK,NaN,0,360.95,ARANI TIRUVANNAMALAI DISTRICT,TAMIL NADU,NaN,False,Easy Ship
15763,402-7668856-0789906,03-31-22,Shipped - Delivered to Buyer,Merchant,JNE3797,JNE3797-KR-M,Western Dress,M,B09SDY8DCT,Shipped,1,761.00,CHENNAI,TAMIL NADU,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
15764,403-5713213-8502730,03-31-22,Shipped - Delivered to Buyer,Merchant,JNE3440,JNE3440-KR-N-M,kurta,M,B081WY1SP3,Shipped,1,379.00,KOLKATA,WEST BENGAL,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
15765,404-9365790-8203566,03-31-22,Shipped - Delivered to Buyer,Merchant,JNE3686,JNE3686-TU-XXL,Top,XXL,B0943KXKSP,Shipped,1,446.00,GANDHINAGAR,Gujarat,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
15766,402-6133022-5893132,03-31-22,Shipped - Delivered to Buyer,Merchant,SET388,SET388-KR-NP-XXL,Set,XXL,B09QJ6676Y,Shipped,1,1271.00,MADURAI,TAMIL NADU,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29450,403-5558293-2033154,06-29-22,Pending,Merchant,J0239,J0239-SKD-XL,Set,XL,B0925WSV76,Unshipped,1,1399.00,NAGAON,ASSAM,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
29451,408-1755769-0715544,06-29-22,Cancelled,Merchant,JNE3294,JNE3294-KR-L,kurta,L,B07R5WM5YR,NaN,0,427.62,SAKLESHPUR,KARNATAKA,NaN,False,Easy Ship
29452,406-2846477-5608365,06-29-22,Pending,Merchant,JNE3725,JNE3725-KR-XXL,kurta,XXL,B09811JFQH,Unshipped,1,442.00,PUNE,MAHARASHTRA,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
29453,408-6225516-9375538,06-29-22,Pending,Merchant,JNE3797,JNE3797-KR-L,Western Dress,L,B09SDXFFQ1,Unshipped,1,0.00,YAMUNANAGAR,HARYANA,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
29454,407-2788756-1507509,06-29-22,Pending,Merchant,JNE3797,JNE3797-KR-L,Western Dress,L,B09SDXFFQ1,Unshipped,1,799.00,NEW DELHI,DELHI,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship

In [21]:
Merchant['Date']=pd.to_datetime(Merchant['Date']).dt.normalize()

C:\Users\anoir\AppData\Local\Temp\ipykernel_17724\2822743112.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Merchant['Date']=pd.to_datetime(Merchant['Date']).dt.normalize()

In [22]:
Merchant['Date'].min()

Timestamp('2022-03-31 00:00:00')

In [23]:
Merchant.info()

<class 'pandas.DataFrame'>
Index: 37552 entries, 0 to 39276
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        37552 non-null  str
 1   Date            37552 non-null  datetime64[us]
 2   Status          37552 non-null  str
 3   Fulfilment      37552 non-null  str
 4   Style           37552 non-null  str
 5   SKU             37552 non-null  str
 6   Category        37552 non-null  str
 7   Size            37552 non-null  str
 8   ASIN            37552 non-null  str
 9   Courier Status  32405 non-null  str
 10  Qty             37552 non-null  int64
 11  Amount          37552 non-null  float64
 12  ship-city       37539 non-null  str
 13  ship-state      37539 non-null  str
 14  promotion-ids   32348 non-null  str
 15  B2B             37552 non-null  bool
 16  fulfilled-by    37552 non-null  str
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), str(13)
memory usage: 50.4 MB

In [24]:
start_date = pd.Timestamp('2022-03-31')
end_date   = pd.Timestamp('2022-06-29')

In [25]:
#outbound
filt=Merchant['Status'].isin(outbound)
Shiprocket_outbound  = (Merchant[filt]['Qty'] * 7 ).sum()
INCREFF_outbound     = (Merchant[filt]['Qty'] * 11 ).sum()

In [26]:
#canceled_stock
filt_canceled= Merchant['Status']=='Cancelled'
temp= Merchant[filt]['Qty'].replace(0,1)
print(temp)
canceled_stock_ship     = (temp[filt]*3 *25).sum()
canceled_stocl_incref   = (temp[filt]*90 *0.15).sum()

1        1
3        1
4        1
5        1
6        1
        ..
39270    1
39271    1
39272    1
39274    1
39276    1
Name: Qty, Length: 30058, dtype: int64

In [27]:
Merchant['Status']=='Cancelled'

0         True
1        False
2         True
3        False
4        False
         ...
39272    False
39273     True
39274    False
39275     True
39276    False
Name: Status, Length: 37552, dtype: bool

In [28]:
#outbound stock
filt= Merchant['Status'].isin(outbound)
days= (Merchant[filt]['Date']- start_date ).dt.days
days= days.replace(0,1)

outbound_stock_ship = (Merchant[filt]['Qty'] * (days/30) * 25).sum()
outbound_stock_ince =  (Merchant[filt]['Qty'] * days * 0.15 ).sum()

In [29]:
#retour stock
filt= Merchant['Status'].isin(retour)
days= (end_date-Merchant[filt]['Date'] ).dt.days
days= days.replace(0,1)
retour_stock_ship = (Merchant[filt]['Qty'] * (days/30) * 25).sum()
retour_stock_ince =  (Merchant[filt]['Qty'] * days * 0.15 ).sum()

In [34]:
#retour cost
filt= Merchant['Status'].isin(retour)
retour_Cost_ship = (Merchant[filt]['Qty'] *  6  ).sum()
retour_Cost_ince = (Merchant[filt]['Qty'] *   15.5   ).sum()

In [45]:
Amazon_merchant_Cost = pd.DataFrame({
    'Cost_element' :['Outbound','Outbound_Storage','Canceled_Storage','Retour_Stock','Retour_Cost'],
    'SHIPROCKET'   :[Shiprocket_outbound,outbound_stock_ship,canceled_stock_ship,retour_stock_ship,retour_Cost_ship],
    'INCREFF'      :[INCREFF_outbound,outbound_stock_ince,canceled_stocl_incref,retour_stock_ince,retour_Cost_ince],
})

In [46]:
Amazon_merchant_Cost

       Cost_element    SHIPROCKET    INCREFF
0          Outbound  2.112670e+05  331991.00
1  Outbound_Storage  1.035396e+06  186371.25
2  Canceled_Storage  2.264175e+06  407551.50
3      Retour_Stock  8.895250e+04   16011.45
4       Retour_Cost  1.278600e+04   33030.50

In [47]:
Amazon_merchant_Cost.to_csv('Shiprocket_vs_INCREFF_Audit.csv', index=False)

In [43]:
#revenu
Filt=Merchant['Status'].isin(outbound)
realized_revenue = (Merchant[Filt]['Qty'] * Merchant[Filt]['Amount']).sum()
print(realized_revenue)

19730792.0

In [61]:
#final check even if its late

Filt=Merchant[Merchant['Status'].isin(outbound)]['SKU']
Merchant[Merchant['Status']=='Cancelled']['SKU'].isin(Merchant[filt]).value_counts()

SKU
False    5136
Name: count, dtype: int64

In [59]:
Merchant.to_csv('merchant.csv',index= False)